### ISSUE TITLE
Integrate with Notion

### ISSUE THREAD

**Issue by attilagyongyosi** [attilagyongyosi/the-bad-request-blog#3]
## Task
- [x] Source pages from a Notion database
- [x] Integrate Markdown styles
- [x] Integrate syntax highlighting support
- [x] Posts are available on their unique URL

**Comment by attilagyongyosi** [comment]
Notion integration has been done, released in **v0.12.1**.
Deployed to https://blog.attilagyongyosi.dev
Example blog post available at https://blog.attilagyongyosi.dev/test-blog-post
I am closing this issue.
