### ISSUE TITLE
Generate and expose RSS feed from blog posts

### ISSUE THREAD

**Issue by attilagyongyosi** [attilagyongyosi/the-bad-request-blog#5]
## Tasks
- [x] RSS feed is available for Notion blog posts publicly
- [x] Readers can subscribe to RSS feed in an RSS client successfully and receive new posts
- [ ] Reader can copy the URL of the feed from any page of the blog
- [ ] Reader can navigate to feed from any page of the blog
